src/objects/Car_Owner__c.object
<CustomObject>
    <fields>
        <fullName>Birthday__c</fullName>
        <label>Birthday</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Passport_Number__c</fullName>
        <label>Passport Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Car Owner</label>
    <nameField>
        <displayFormat>CO-{00000}</displayFormat>
        <label>Car Owner Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Car Owners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TriggerTest.cls
@isTest
private class TriggerTest {
    @isTest static void CarOwnerTest () {
        Car_Owner__c newCarOwner = new Car_Owner__c(
        Birthday__c=Date.today().addDays(-3),
            First_Name__c='Ilia',
            Last_Name__c='Lud',
            Passport_Number__c='hfkclh'
        );
        INSERT newCarOwner;
        Car_Owner__c newCarOwner2 = new Car_Owner__c(
        Birthday__c=Date.today().addDays(-3),
            First_Name__c='Olia',
            Last_Name__c='Ruf',
            Passport_Number__c='hfkclh'
        );
        INSERT newCarOwner2;
        
    }
}