src/objects/Car__c.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Car_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Car Owner</label>
        <referenceTo>Car_Owner__c</referenceTo>
        <relationshipLabel>Cars</relationshipLabel>
        <relationshipName>Cars</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Due_data__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Parking__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parking</label>
        <referenceTo>Parking__c</referenceTo>
        <relationshipLabel>Cars</relationshipLabel>
        <relationshipName>Cars</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Release__c</fullName>
        <label>Release</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Parking</fullName>
                </value>
                <value>
                    <fullName>Auction</fullName>
                </value>
                <value>
                    <fullName>Paid Fine</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Car_Owner__c.object
<CustomObject>
    <label>Car Owner</label>
    <nameField>
        <displayFormat>CO-{00000}</displayFormat>
        <label>Car Owner Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Car Owners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Parking__c.object
<CustomObject>
    <label>Parking</label>
    <nameField>
        <displayFormat>PK-{00000}</displayFormat>
        <label>Parking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ParkingViewController.cls
public class ParkingViewController {
    public List<Parking__c> parkingList {get;set;}
    public List<SelectOption>  parkingSelectOptionList {get;set;}
    public List<Car__c> carList {get;set;}
    public String parkingId{get;set;}
    public ParkingViewController () {
        ParkingList = [SELECT id, Name FROM Parking__c ORDER BY Name];
        parkingId=ParkingList.isEmpty()== FALSE ? ParkingList[0].id : NULL;
        parkingSelectOptionList=new List<SelectOption>();
        for(Parking__c item : ParkingList){
            parkingSelectOptionList.add(new SelectOption(item.id, item.Name));
        }
       getCars();
        
    }
    public void getCars(){
        carList=[
            SELECT id, Name, Brand__c, Car_Owner__c, Due_data__c, Parking__c, Price__c, Release__c, Status__c 
            FROM Car__c
            WHERE Status__c='In Parking'
            AND Parking__r.id = : parkingId
        ];   
    }
    

}