src/objects/Errors_Log__c.object
<CustomObject>
    <fields>
        <fullName>Error_Class__c</fullName>
        <label>Error Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Error_Code__c</fullName>
        <label>Error Code</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Error_Massage__c</fullName>
        <label>Error Massage</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Error_Method__c</fullName>
        <label>Error Method</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Error_Type__c</fullName>
        <label>Error Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Errors Log</label>
    <nameField>
        <displayFormat>ERROR-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Errors Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ErrorTask.cls
/**
 * Created by akireyeu on 20.11.2019.
 */

global with sharing class ErrorTask {

    global static String insertError(Exception e) {
        String str;
        String stackTrace = e.getStackTraceString().substringBefore('\n');
        String className = stackTrace.substringAfter('.').substringBefore('.');
        String methodName = stackTrace.substringBefore(':').substringAfter(className).substringAfter('.');
        Errors_Log__c err = new Errors_Log__c();
        err.Error_Massage__c = e.getMessage();
        err.Error_Type__c = e.getTypeName();
        err.Error_Code__c = e.getLineNumber();
        err.Error_Method__c = methodName;
        err.Error_Class__c = className;
        database.insert(err);
        if (e.getMessage().contains('Custom Error')) {
          str = e.getMessage();
        }
        else {
            str = ErrorTaskMap.getValue(e.getTypeName());
        }
        return str;
    }
}