src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dislike__c</fullName>
        <label>Dislike</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Like__c</fullName>
        <label>Like</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Views__c</fullName>
        <label>Views</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Review__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dislike__c</fullName>
        <label>Dislike</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Like__c</fullName>
        <label>Like</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Reviews</relationshipLabel>
        <relationshipName>Reviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Views__c</fullName>
        <label>Views</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Review</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Review</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ArtTaskProductTableApex.cls
/**
 * Created by akireyeu on 24.12.2019.
 */

public with sharing class ArtTaskProductTableApex {
//    @AuraEnabled
//    public static List<Review__c> getReview(String id)
//    {
//        return [SELECT Id, Description__c, Views__c, Like__c, Dislike__c FROM Review__c  WHERE Product__r.Id=:id];
//    }
//    @AuraEnabled
//    public static void setLike(String id)
//    {
//        Review__c r = [SELECT Id, Views__c, Like__c, Dislike__c FROM Review__c  WHERE Review__c.Id=:id];
//        r.Like__c++;
//        update r;
//    }
//    @AuraEnabled
//    public static void setDislike(String id)
//    {
//        Review__c r = [SELECT Id, Views__c, Like__c, Dislike__c FROM Review__c  WHERE Review__c.Id=:id];
//        r.Dislike__c++;
//        update r;
//    }
}