src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dislike__c</fullName>
        <label>Dislike</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Like__c</fullName>
        <label>Like</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Views__c</fullName>
        <label>Views</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Review__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dislike__c</fullName>
        <label>Dislike</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Like__c</fullName>
        <label>Like</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Reviews</relationshipLabel>
        <relationshipName>Reviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Views__c</fullName>
        <label>Views</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Review</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Review</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TreeApex.cls
/**
 * Created by AlexanderKireev on 4/2/2020.
 */

public with sharing class TreeApex {
    @AuraEnabled(Cacheable=true)
    public static List<TreeWrapper> getTreeData(){
        List<Product__c> productsList = [SELECT Id, Name, Description__c, Like__c, Dislike__c, Views__c, (SELECT Id,
        Name, Description__c, Like__c, Dislike__c, Views__c FROM Reviews__r) FROM Product__c];
        List<TreeWrapper> productsListWrapper = new List<TreeWrapper>();
        for(Product__c product : productsList){
            TreeWrapper treeWrapperItem = new TreeWrapper();
            treeWrapperItem.name = product.Name;
            treeWrapperItem.label = product.Name;
            treeWrapperItem.href = '/'+product.id;
            treeWrapperItem.expanded = true;
            List<TreeWrapper> reviewsList = new List<TreeWrapper>();
            for(Review__c review : product.Reviews__r){
                TreeWrapper reviewWrapper = new TreeWrapper();
                reviewWrapper.name = review.Id;
                reviewWrapper.label = review.Name;
                reviewWrapper.href = '/'+review.id;
                reviewWrapper.expanded = true;
                reviewWrapper.items = new List<TreeWrapper>();
                reviewsList.add(reviewWrapper);
            }
            treeWrapperItem.items = reviewsList;
            productsListWrapper.add(treeWrapperItem);
        }
        return productsListWrapper;
    }
}